x-shared_environment: &shared_environment
    LOG_LEVEL: ${LOG_LEVEL:-debug}

services:
    app:
        # Replace this line by the ones commented below to build the image from the repository.
        image: kevinrpb/swift-twitch-chat-colors:latest
        # image: swift-twitch-chat-colors:latest
        # build:
        #     context: https://github.com/kevinrpb/swift-twitch-chat-colors.git
        environment:
            <<: *shared_environment
        # Uncomment to mount a directory. This is useful if you use a file DB.
        # volumes:
        #     - ./db_data/:/db_data/
        ports:
            - "8080:8080"
        command: [
            "--hostname", "0.0.0.0",
            "--port", "8080",
            # Uncomment and remove next line to use a file as DB instead of memory
            # "--db-path", "/db_data/db.sqlite",
            "--db-memory",
            "-c", "kevinrpb"
        ]
